export type SportBadgeTier = "bronze" | "silver" | "gold" | "diamond" | "elite";

export type SportBadgeAsset = {
  badge_id: string;
  sort_order: number;
  category: string;
  category_slug: string;
  tier: SportBadgeTier;
  tier_rank: number;
  filename: string;
  src: string;
  ui_title: string;
  ui_subtitle: string;
  proof_label: string;
  tagline_key: string;
};

const SPORT_BADGE_TIERS = ["bronze", "silver", "gold", "diamond", "elite"] as const satisfies readonly SportBadgeTier[];

export const SPORT_BADGE_ASSETS = [
  {
    badge_id: "running-bronze",
    sort_order: 1,
    category: "Running",
    category_slug: "running",
    tier: "bronze" as SportBadgeTier,
    tier_rank: 1,
    filename: "xionid-badge-running-bronze.webp",
    src: "/badges/sport/xionid-badge-running-bronze.webp",
    ui_title: "Running Lifestyle Starter",
    ui_subtitle: "Entry-level verified running lifestyle",
    proof_label: "Running starter proof",
    tagline_key: "badges.running.bronze",
  },
  {
    badge_id: "running-silver",
    sort_order: 2,
    category: "Running",
    category_slug: "running",
    tier: "silver" as SportBadgeTier,
    tier_rank: 2,
    filename: "xionid-badge-running-silver.webp",
    src: "/badges/sport/xionid-badge-running-silver.webp",
    ui_title: "Weekly Running Builder",
    ui_subtitle: "Consistent weekly running habit",
    proof_label: "Weekly running proof",
    tagline_key: "badges.running.silver",
  },
  {
    badge_id: "running-gold",
    sort_order: 3,
    category: "Running",
    category_slug: "running",
    tier: "gold" as SportBadgeTier,
    tier_rank: 3,
    filename: "xionid-badge-running-gold.webp",
    src: "/badges/sport/xionid-badge-running-gold.webp",
    ui_title: "Progressive Running Signal",
    ui_subtitle: "Clear progressive running signal and activity momentum",
    proof_label: "Progressive running proof",
    tagline_key: "badges.running.gold",
  },
  {
    badge_id: "running-diamond",
    sort_order: 4,
    category: "Running",
    category_slug: "running",
    tier: "diamond" as SportBadgeTier,
    tier_rank: 4,
    filename: "xionid-badge-running-diamond.webp",
    src: "/badges/sport/xionid-badge-running-diamond.webp",
    ui_title: "Running Discipline Proof",
    ui_subtitle: "Strong verified running discipline",
    proof_label: "Running discipline proof",
    tagline_key: "badges.running.diamond",
  },
  {
    badge_id: "running-elite",
    sort_order: 5,
    category: "Running",
    category_slug: "running",
    tier: "elite" as SportBadgeTier,
    tier_rank: 5,
    filename: "xionid-badge-running-elite.webp",
    src: "/badges/sport/xionid-badge-running-elite.webp",
    ui_title: "Running Lifestyle Ambassador",
    ui_subtitle: "Top-tier running identity and ambassador energy",
    proof_label: "Running ambassador proof",
    tagline_key: "badges.running.elite",
  },
  {
    badge_id: "strength-bronze",
    sort_order: 6,
    category: "Strength",
    category_slug: "strength",
    tier: "bronze" as SportBadgeTier,
    tier_rank: 1,
    filename: "xionid-badge-strength-bronze.webp",
    src: "/badges/sport/xionid-badge-strength-bronze.webp",
    ui_title: "Strength Lifestyle Starter",
    ui_subtitle: "Entry-level verified strength lifestyle",
    proof_label: "Strength starter proof",
    tagline_key: "badges.strength.bronze",
  },
  {
    badge_id: "strength-silver",
    sort_order: 7,
    category: "Strength",
    category_slug: "strength",
    tier: "silver" as SportBadgeTier,
    tier_rank: 2,
    filename: "xionid-badge-strength-silver.webp",
    src: "/badges/sport/xionid-badge-strength-silver.webp",
    ui_title: "Weekly Strength Builder",
    ui_subtitle: "Consistent weekly strength training habit",
    proof_label: "Weekly strength proof",
    tagline_key: "badges.strength.silver",
  },
  {
    badge_id: "strength-gold",
    sort_order: 8,
    category: "Strength",
    category_slug: "strength",
    tier: "gold" as SportBadgeTier,
    tier_rank: 3,
    filename: "xionid-badge-strength-gold.webp",
    src: "/badges/sport/xionid-badge-strength-gold.webp",
    ui_title: "Progressive Strength Signal",
    ui_subtitle: "Clear progression in strength lifestyle",
    proof_label: "Progressive strength proof",
    tagline_key: "badges.strength.gold",
  },
  {
    badge_id: "strength-diamond",
    sort_order: 9,
    category: "Strength",
    category_slug: "strength",
    tier: "diamond" as SportBadgeTier,
    tier_rank: 4,
    filename: "xionid-badge-strength-diamond.webp",
    src: "/badges/sport/xionid-badge-strength-diamond.webp",
    ui_title: "Strength Discipline Proof",
    ui_subtitle: "Strong verified discipline in strength training",
    proof_label: "Strength discipline proof",
    tagline_key: "badges.strength.diamond",
  },
  {
    badge_id: "strength-elite",
    sort_order: 10,
    category: "Strength",
    category_slug: "strength",
    tier: "elite" as SportBadgeTier,
    tier_rank: 5,
    filename: "xionid-badge-strength-elite.webp",
    src: "/badges/sport/xionid-badge-strength-elite.webp",
    ui_title: "Strength Lifestyle Ambassador",
    ui_subtitle: "Top-tier strength lifestyle reputation",
    proof_label: "Strength ambassador proof",
    tagline_key: "badges.strength.elite",
  },
  {
    badge_id: "cycling-bronze",
    sort_order: 11,
    category: "Cycling",
    category_slug: "cycling",
    tier: "bronze" as SportBadgeTier,
    tier_rank: 1,
    filename: "xionid-badge-cycling-bronze.webp",
    src: "/badges/sport/xionid-badge-cycling-bronze.webp",
    ui_title: "Cycling Lifestyle Starter",
    ui_subtitle: "Entry-level verified cycling lifestyle",
    proof_label: "Cycling starter proof",
    tagline_key: "badges.cycling.bronze",
  },
  {
    badge_id: "cycling-silver",
    sort_order: 12,
    category: "Cycling",
    category_slug: "cycling",
    tier: "silver" as SportBadgeTier,
    tier_rank: 2,
    filename: "xionid-badge-cycling-silver.webp",
    src: "/badges/sport/xionid-badge-cycling-silver.webp",
    ui_title: "Weekly Cycling Builder",
    ui_subtitle: "Consistent cycling habit",
    proof_label: "Weekly cycling proof",
    tagline_key: "badges.cycling.silver",
  },
  {
    badge_id: "cycling-gold",
    sort_order: 13,
    category: "Cycling",
    category_slug: "cycling",
    tier: "gold" as SportBadgeTier,
    tier_rank: 3,
    filename: "xionid-badge-cycling-gold.webp",
    src: "/badges/sport/xionid-badge-cycling-gold.webp",
    ui_title: "Progressive Cycling Signal",
    ui_subtitle: "Clear cycling momentum and progression",
    proof_label: "Progressive cycling proof",
    tagline_key: "badges.cycling.gold",
  },
  {
    badge_id: "cycling-diamond",
    sort_order: 14,
    category: "Cycling",
    category_slug: "cycling",
    tier: "diamond" as SportBadgeTier,
    tier_rank: 4,
    filename: "xionid-badge-cycling-diamond.webp",
    src: "/badges/sport/xionid-badge-cycling-diamond.webp",
    ui_title: "Cycling Discipline Proof",
    ui_subtitle: "Strong verified cycling discipline",
    proof_label: "Cycling discipline proof",
    tagline_key: "badges.cycling.diamond",
  },
  {
    badge_id: "cycling-elite",
    sort_order: 15,
    category: "Cycling",
    category_slug: "cycling",
    tier: "elite" as SportBadgeTier,
    tier_rank: 5,
    filename: "xionid-badge-cycling-elite.webp",
    src: "/badges/sport/xionid-badge-cycling-elite.webp",
    ui_title: "Cycling Lifestyle Ambassador",
    ui_subtitle: "Top-tier cycling identity",
    proof_label: "Cycling ambassador proof",
    tagline_key: "badges.cycling.elite",
  },
  {
    badge_id: "swimming-bronze",
    sort_order: 16,
    category: "Swimming",
    category_slug: "swimming",
    tier: "bronze" as SportBadgeTier,
    tier_rank: 1,
    filename: "xionid-badge-swimming-bronze.webp",
    src: "/badges/sport/xionid-badge-swimming-bronze.webp",
    ui_title: "Swimming Lifestyle Starter",
    ui_subtitle: "Entry-level verified swimming lifestyle",
    proof_label: "Swimming starter proof",
    tagline_key: "badges.swimming.bronze",
  },
  {
    badge_id: "swimming-silver",
    sort_order: 17,
    category: "Swimming",
    category_slug: "swimming",
    tier: "silver" as SportBadgeTier,
    tier_rank: 2,
    filename: "xionid-badge-swimming-silver.webp",
    src: "/badges/sport/xionid-badge-swimming-silver.webp",
    ui_title: "Weekly Swimming Builder",
    ui_subtitle: "Consistent swimming routine",
    proof_label: "Weekly swimming proof",
    tagline_key: "badges.swimming.silver",
  },
  {
    badge_id: "swimming-gold",
    sort_order: 18,
    category: "Swimming",
    category_slug: "swimming",
    tier: "gold" as SportBadgeTier,
    tier_rank: 3,
    filename: "xionid-badge-swimming-gold.webp",
    src: "/badges/sport/xionid-badge-swimming-gold.webp",
    ui_title: "Progressive Swimming Signal",
    ui_subtitle: "Clear swimming progression",
    proof_label: "Progressive swimming proof",
    tagline_key: "badges.swimming.gold",
  },
  {
    badge_id: "swimming-diamond",
    sort_order: 19,
    category: "Swimming",
    category_slug: "swimming",
    tier: "diamond" as SportBadgeTier,
    tier_rank: 4,
    filename: "xionid-badge-swimming-diamond.webp",
    src: "/badges/sport/xionid-badge-swimming-diamond.webp",
    ui_title: "Swimming Discipline Proof",
    ui_subtitle: "Strong verified swim discipline",
    proof_label: "Swimming discipline proof",
    tagline_key: "badges.swimming.diamond",
  },
  {
    badge_id: "swimming-elite",
    sort_order: 20,
    category: "Swimming",
    category_slug: "swimming",
    tier: "elite" as SportBadgeTier,
    tier_rank: 5,
    filename: "xionid-badge-swimming-elite.webp",
    src: "/badges/sport/xionid-badge-swimming-elite.webp",
    ui_title: "Swimming Lifestyle Ambassador",
    ui_subtitle: "Top-tier swimming lifestyle reputation",
    proof_label: "Swimming ambassador proof",
    tagline_key: "badges.swimming.elite",
  },
  {
    badge_id: "hybrid-bronze",
    sort_order: 21,
    category: "Hybrid",
    category_slug: "hybrid",
    tier: "bronze" as SportBadgeTier,
    tier_rank: 1,
    filename: "xionid-badge-hybrid-bronze.webp",
    src: "/badges/sport/xionid-badge-hybrid-bronze.webp",
    ui_title: "Hybrid Lifestyle Starter",
    ui_subtitle: "Entry-level hybrid athlete identity",
    proof_label: "Hybrid starter proof",
    tagline_key: "badges.hybrid.bronze",
  },
  {
    badge_id: "hybrid-silver",
    sort_order: 22,
    category: "Hybrid",
    category_slug: "hybrid",
    tier: "silver" as SportBadgeTier,
    tier_rank: 2,
    filename: "xionid-badge-hybrid-silver.webp",
    src: "/badges/sport/xionid-badge-hybrid-silver.webp",
    ui_title: "Multi-Sport Builder",
    ui_subtitle: "Consistent hybrid training pattern",
    proof_label: "Multi-sport builder proof",
    tagline_key: "badges.hybrid.silver",
  },
  {
    badge_id: "hybrid-gold",
    sort_order: 23,
    category: "Hybrid",
    category_slug: "hybrid",
    tier: "gold" as SportBadgeTier,
    tier_rank: 3,
    filename: "xionid-badge-hybrid-gold.webp",
    src: "/badges/sport/xionid-badge-hybrid-gold.webp",
    ui_title: "Hybrid Performance Signal",
    ui_subtitle: "Clear multi-sport progression",
    proof_label: "Hybrid performance proof",
    tagline_key: "badges.hybrid.gold",
  },
  {
    badge_id: "hybrid-diamond",
    sort_order: 24,
    category: "Hybrid",
    category_slug: "hybrid",
    tier: "diamond" as SportBadgeTier,
    tier_rank: 4,
    filename: "xionid-badge-hybrid-diamond.webp",
    src: "/badges/sport/xionid-badge-hybrid-diamond.webp",
    ui_title: "Hybrid Discipline Proof",
    ui_subtitle: "Strong verified hybrid athlete discipline",
    proof_label: "Hybrid discipline proof",
    tagline_key: "badges.hybrid.diamond",
  },
  {
    badge_id: "hybrid-elite",
    sort_order: 25,
    category: "Hybrid",
    category_slug: "hybrid",
    tier: "elite" as SportBadgeTier,
    tier_rank: 5,
    filename: "xionid-badge-hybrid-elite.webp",
    src: "/badges/sport/xionid-badge-hybrid-elite.webp",
    ui_title: "Hybrid Lifestyle Ambassador",
    ui_subtitle: "Top-tier hybrid athlete identity",
    proof_label: "Hybrid ambassador proof",
    tagline_key: "badges.hybrid.elite",
  },
  {
    badge_id: "marathon-events-bronze",
    sort_order: 26,
    category: "Marathon / Events",
    category_slug: "marathon-events",
    tier: "bronze" as SportBadgeTier,
    tier_rank: 1,
    filename: "xionid-badge-marathon-events-bronze.webp",
    src: "/badges/sport/xionid-badge-marathon-events-bronze.webp",
    ui_title: "Marathon Lifestyle Starter",
    ui_subtitle: "Entry-level marathon/events participation lifestyle",
    proof_label: "Marathon starter proof",
    tagline_key: "badges.marathon-events.bronze",
  },
  {
    badge_id: "marathon-events-silver",
    sort_order: 27,
    category: "Marathon / Events",
    category_slug: "marathon-events",
    tier: "silver" as SportBadgeTier,
    tier_rank: 2,
    filename: "xionid-badge-marathon-events-silver.webp",
    src: "/badges/sport/xionid-badge-marathon-events-silver.webp",
    ui_title: "Event Readiness Builder",
    ui_subtitle: "Consistent event preparation and attendance",
    proof_label: "Event readiness proof",
    tagline_key: "badges.marathon-events.silver",
  },
  {
    badge_id: "marathon-events-gold",
    sort_order: 28,
    category: "Marathon / Events",
    category_slug: "marathon-events",
    tier: "gold" as SportBadgeTier,
    tier_rank: 3,
    filename: "xionid-badge-marathon-events-gold.webp",
    src: "/badges/sport/xionid-badge-marathon-events-gold.webp",
    ui_title: "Endurance Event Signal",
    ui_subtitle: "Clear endurance event progression",
    proof_label: "Endurance event proof",
    tagline_key: "badges.marathon-events.gold",
  },
  {
    badge_id: "marathon-events-diamond",
    sort_order: 29,
    category: "Marathon / Events",
    category_slug: "marathon-events",
    tier: "diamond" as SportBadgeTier,
    tier_rank: 4,
    filename: "xionid-badge-marathon-events-diamond.webp",
    src: "/badges/sport/xionid-badge-marathon-events-diamond.webp",
    ui_title: "Event Discipline Proof",
    ui_subtitle: "Strong verified discipline in event-based endurance lifestyle",
    proof_label: "Event discipline proof",
    tagline_key: "badges.marathon-events.diamond",
  },
  {
    badge_id: "marathon-events-elite",
    sort_order: 30,
    category: "Marathon / Events",
    category_slug: "marathon-events",
    tier: "elite" as SportBadgeTier,
    tier_rank: 5,
    filename: "xionid-badge-marathon-events-elite.webp",
    src: "/badges/sport/xionid-badge-marathon-events-elite.webp",
    ui_title: "Marathon Lifestyle Ambassador",
    ui_subtitle: "Top-tier marathon/events ambassador identity",
    proof_label: "Marathon ambassador proof",
    tagline_key: "badges.marathon-events.elite",
  },
  {
    badge_id: "recovery-bronze",
    sort_order: 31,
    category: "Recovery",
    category_slug: "recovery",
    tier: "bronze" as SportBadgeTier,
    tier_rank: 1,
    filename: "xionid-badge-recovery-bronze.webp",
    src: "/badges/sport/xionid-badge-recovery-bronze.webp",
    ui_title: "Recovery Lifestyle Starter",
    ui_subtitle: "Entry-level recovery-focused lifestyle",
    proof_label: "Recovery starter proof",
    tagline_key: "badges.recovery.bronze",
  },
  {
    badge_id: "recovery-silver",
    sort_order: 32,
    category: "Recovery",
    category_slug: "recovery",
    tier: "silver" as SportBadgeTier,
    tier_rank: 2,
    filename: "xionid-badge-recovery-silver.webp",
    src: "/badges/sport/xionid-badge-recovery-silver.webp",
    ui_title: "Recovery Rhythm Builder",
    ui_subtitle: "Consistent recovery habits",
    proof_label: "Recovery rhythm proof",
    tagline_key: "badges.recovery.silver",
  },
  {
    badge_id: "recovery-gold",
    sort_order: 33,
    category: "Recovery",
    category_slug: "recovery",
    tier: "gold" as SportBadgeTier,
    tier_rank: 3,
    filename: "xionid-badge-recovery-gold.webp",
    src: "/badges/sport/xionid-badge-recovery-gold.webp",
    ui_title: "Regeneration Signal",
    ui_subtitle: "Clear recovery and regeneration signal",
    proof_label: "Regeneration proof",
    tagline_key: "badges.recovery.gold",
  },
  {
    badge_id: "recovery-diamond",
    sort_order: 34,
    category: "Recovery",
    category_slug: "recovery",
    tier: "diamond" as SportBadgeTier,
    tier_rank: 4,
    filename: "xionid-badge-recovery-diamond.webp",
    src: "/badges/sport/xionid-badge-recovery-diamond.webp",
    ui_title: "Recovery Discipline Proof",
    ui_subtitle: "Strong verified recovery discipline",
    proof_label: "Recovery discipline proof",
    tagline_key: "badges.recovery.diamond",
  },
  {
    badge_id: "recovery-elite",
    sort_order: 35,
    category: "Recovery",
    category_slug: "recovery",
    tier: "elite" as SportBadgeTier,
    tier_rank: 5,
    filename: "xionid-badge-recovery-elite.webp",
    src: "/badges/sport/xionid-badge-recovery-elite.webp",
    ui_title: "Recovery Lifestyle Ambassador",
    ui_subtitle: "Top-tier recovery identity",
    proof_label: "Recovery ambassador proof",
    tagline_key: "badges.recovery.elite",
  },
  {
    badge_id: "wellness-bronze",
    sort_order: 36,
    category: "Wellness",
    category_slug: "wellness",
    tier: "bronze" as SportBadgeTier,
    tier_rank: 1,
    filename: "xionid-badge-wellness-bronze.webp",
    src: "/badges/sport/xionid-badge-wellness-bronze.webp",
    ui_title: "Wellness Lifestyle Starter",
    ui_subtitle: "Entry-level wellness-focused lifestyle",
    proof_label: "Wellness starter proof",
    tagline_key: "badges.wellness.bronze",
  },
  {
    badge_id: "wellness-silver",
    sort_order: 37,
    category: "Wellness",
    category_slug: "wellness",
    tier: "silver" as SportBadgeTier,
    tier_rank: 2,
    filename: "xionid-badge-wellness-silver.webp",
    src: "/badges/sport/xionid-badge-wellness-silver.webp",
    ui_title: "Wellness Habit Builder",
    ui_subtitle: "Consistent wellness habits",
    proof_label: "Wellness habit proof",
    tagline_key: "badges.wellness.silver",
  },
  {
    badge_id: "wellness-gold",
    sort_order: 38,
    category: "Wellness",
    category_slug: "wellness",
    tier: "gold" as SportBadgeTier,
    tier_rank: 3,
    filename: "xionid-badge-wellness-gold.webp",
    src: "/badges/sport/xionid-badge-wellness-gold.webp",
    ui_title: "Wellness Rhythm Signal",
    ui_subtitle: "Clear wellness and longevity rhythm",
    proof_label: "Wellness rhythm proof",
    tagline_key: "badges.wellness.gold",
  },
  {
    badge_id: "wellness-diamond",
    sort_order: 39,
    category: "Wellness",
    category_slug: "wellness",
    tier: "diamond" as SportBadgeTier,
    tier_rank: 4,
    filename: "xionid-badge-wellness-diamond.webp",
    src: "/badges/sport/xionid-badge-wellness-diamond.webp",
    ui_title: "Wellness Discipline Proof",
    ui_subtitle: "Strong verified wellness discipline",
    proof_label: "Wellness discipline proof",
    tagline_key: "badges.wellness.diamond",
  },
  {
    badge_id: "wellness-elite",
    sort_order: 40,
    category: "Wellness",
    category_slug: "wellness",
    tier: "elite" as SportBadgeTier,
    tier_rank: 5,
    filename: "xionid-badge-wellness-elite.webp",
    src: "/badges/sport/xionid-badge-wellness-elite.webp",
    ui_title: "Wellness Lifestyle Ambassador",
    ui_subtitle: "Top-tier wellness identity",
    proof_label: "Wellness ambassador proof",
    tagline_key: "badges.wellness.elite",
  },
  {
    badge_id: "gear-bronze",
    sort_order: 41,
    category: "Gear",
    category_slug: "gear",
    tier: "bronze" as SportBadgeTier,
    tier_rank: 1,
    filename: "xionid-badge-gear-bronze.webp",
    src: "/badges/sport/xionid-badge-gear-bronze.webp",
    ui_title: "Gear Lifestyle Starter",
    ui_subtitle: "Entry-level sports gear lifestyle",
    proof_label: "Gear starter proof",
    tagline_key: "badges.gear.bronze",
  },
  {
    badge_id: "gear-silver",
    sort_order: 42,
    category: "Gear",
    category_slug: "gear",
    tier: "silver" as SportBadgeTier,
    tier_rank: 2,
    filename: "xionid-badge-gear-silver.webp",
    src: "/badges/sport/xionid-badge-gear-silver.webp",
    ui_title: "Smart Gear Builder",
    ui_subtitle: "Consistent engagement with performance gear",
    proof_label: "Smart gear proof",
    tagline_key: "badges.gear.silver",
  },
  {
    badge_id: "gear-gold",
    sort_order: 43,
    category: "Gear",
    category_slug: "gear",
    tier: "gold" as SportBadgeTier,
    tier_rank: 3,
    filename: "xionid-badge-gear-gold.webp",
    src: "/badges/sport/xionid-badge-gear-gold.webp",
    ui_title: "Performance Gear Signal",
    ui_subtitle: "Clear performance gear identity",
    proof_label: "Performance gear proof",
    tagline_key: "badges.gear.gold",
  },
  {
    badge_id: "gear-diamond",
    sort_order: 44,
    category: "Gear",
    category_slug: "gear",
    tier: "diamond" as SportBadgeTier,
    tier_rank: 4,
    filename: "xionid-badge-gear-diamond.webp",
    src: "/badges/sport/xionid-badge-gear-diamond.webp",
    ui_title: "Trusted Gear Proof",
    ui_subtitle: "Strong verified gear lifestyle proof",
    proof_label: "Trusted gear proof",
    tagline_key: "badges.gear.diamond",
  },
  {
    badge_id: "gear-elite",
    sort_order: 45,
    category: "Gear",
    category_slug: "gear",
    tier: "elite" as SportBadgeTier,
    tier_rank: 5,
    filename: "xionid-badge-gear-elite.webp",
    src: "/badges/sport/xionid-badge-gear-elite.webp",
    ui_title: "Gear Lifestyle Ambassador",
    ui_subtitle: "Top-tier sports gear lifestyle identity",
    proof_label: "Gear ambassador proof",
    tagline_key: "badges.gear.elite",
  },
  {
    badge_id: "supplements-bronze",
    sort_order: 46,
    category: "Supplements",
    category_slug: "supplements",
    tier: "bronze" as SportBadgeTier,
    tier_rank: 1,
    filename: "xionid-badge-supplements-bronze.webp",
    src: "/badges/sport/xionid-badge-supplements-bronze.webp",
    ui_title: "Supplement Lifestyle Starter",
    ui_subtitle: "Entry-level supplement/recovery stack lifestyle",
    proof_label: "Supplement starter proof",
    tagline_key: "badges.supplements.bronze",
  },
  {
    badge_id: "supplements-silver",
    sort_order: 47,
    category: "Supplements",
    category_slug: "supplements",
    tier: "silver" as SportBadgeTier,
    tier_rank: 2,
    filename: "xionid-badge-supplements-silver.webp",
    src: "/badges/sport/xionid-badge-supplements-silver.webp",
    ui_title: "Recovery Stack Builder",
    ui_subtitle: "Consistent supplement/recovery stack habit",
    proof_label: "Recovery stack proof",
    tagline_key: "badges.supplements.silver",
  },
  {
    badge_id: "supplements-gold",
    sort_order: 48,
    category: "Supplements",
    category_slug: "supplements",
    tier: "gold" as SportBadgeTier,
    tier_rank: 3,
    filename: "xionid-badge-supplements-gold.webp",
    src: "/badges/sport/xionid-badge-supplements-gold.webp",
    ui_title: "Clean Fuel Signal",
    ui_subtitle: "Clear supplementation and fuel signal",
    proof_label: "Clean fuel proof",
    tagline_key: "badges.supplements.gold",
  },
  {
    badge_id: "supplements-diamond",
    sort_order: 49,
    category: "Supplements",
    category_slug: "supplements",
    tier: "diamond" as SportBadgeTier,
    tier_rank: 4,
    filename: "xionid-badge-supplements-diamond.webp",
    src: "/badges/sport/xionid-badge-supplements-diamond.webp",
    ui_title: "Supplement Discipline Proof",
    ui_subtitle: "Strong verified supplement discipline",
    proof_label: "Supplement discipline proof",
    tagline_key: "badges.supplements.diamond",
  },
  {
    badge_id: "supplements-elite",
    sort_order: 50,
    category: "Supplements",
    category_slug: "supplements",
    tier: "elite" as SportBadgeTier,
    tier_rank: 5,
    filename: "xionid-badge-supplements-elite.webp",
    src: "/badges/sport/xionid-badge-supplements-elite.webp",
    ui_title: "Supplement Lifestyle Ambassador",
    ui_subtitle: "Top-tier supplement/recovery stack identity",
    proof_label: "Supplement ambassador proof",
    tagline_key: "badges.supplements.elite",
  },
] as const satisfies readonly SportBadgeAsset[];

const normalizeSportBadgeKey = (value: string) => value.trim().toLowerCase();

const isSportBadgeTier = (value: string): value is SportBadgeTier =>
  SPORT_BADGE_TIERS.includes(normalizeSportBadgeKey(value) as SportBadgeTier);

export const getSportBadgeAsset = (categorySlug: string, tier: string): SportBadgeAsset | null => {
  const normalizedCategorySlug = normalizeSportBadgeKey(categorySlug);
  const normalizedTier = normalizeSportBadgeKey(tier);

  if (!normalizedCategorySlug || !isSportBadgeTier(normalizedTier)) return null;

  return (
    SPORT_BADGE_ASSETS.find(
      (asset) => asset.category_slug === normalizedCategorySlug && asset.tier === normalizedTier,
    ) ?? null
  );
};

export const getSportBadgeAssetSrc = (categorySlug: string, tier: string): string | null =>
  getSportBadgeAsset(categorySlug, tier)?.src ?? null;
